---
AWSTemplateFormatVersion: '2010-09-09'
Description: Unreal Engine 4 Pixel Streaming on AWS Solution
Parameters:
  AvailabilityZone:
    Description: AvailabilityZone to create EC2 instance
    Type: String
    Default: ''
  KeyPairName:
    Description: Keypair associated with the EC2 instance
    Type: AWS::EC2::KeyPair::KeyName
    MinLength: '1'
    ConstraintDescription: Must provide a keypair to be associated with the EC2 instance
  AMIId:
    Description: AMI ID to be use with EC2 instance
    Type: String
  SubnetId:
    Type: String
    Default: ''
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: g4dn.2xlarge
    AllowedValues:
    - g4dn.xlarge
    - g4dn.2xlarge
    - g4dn.4xlarge
    - g4dn.8xlarge
    - g4dn.12xlarge
    - g4dn.16xlarge
  SecurityGroupId:
    Type: String
#   PixelStreamingAccessCIDR:
#     Description: CIDR Block from which the Pixel Streaming Server will be accessible.
#     Default: 0.0.0.0/0
#     Type: String
#     AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
#     ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-32
#   NiceDCVAccessCIDR:
#     Description: CIDR Block from which the NICE DCV Remote Desktop will be accessible.
#     Default: 0.0.0.0/0
#     Type: String
#     AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
#     ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-32
#   PixelStreamerBuildLocation:
#     Type: String
#     Description: Location of zip file of UE4 Pixel Streaming exported project. Format
#       of https://bucket-name.region.amazonaws.com/Path/UE4PixelStreamingProject.zip
#   PixelStreamerBootstrapLocation:
#     Type: String
#     Description: Location of bootstrap Powershell script. Format of https://bucket-name.region.amazonaws.com/Path/UE4-Pixel-Streamer-Bootstrap.ps1



Resources:
  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: String
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroupIds: 
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      InstanceProfile: !GetAtt RootInstanceProfile
      UserData: String
   
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DcvInstallAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:*
          - s3:*
          Resource: "*"
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: arn:aws:s3::*
      Roles:
      - Ref: RootRole
    Metadata:
      AWS::CloudFormation::Designer:
        id: 7160187f-0a7e-451f-bcb1-85783245c504
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: RootRole


        
# Outputs:
#   WindowsInstanceId:
#     Value:
#       Ref: WindowsInstance
#     Condition: CreateWindows
#     Description: Instance ID for the newly created EC2 instance
#   WindowsPublicDNS:
#     Value:
#       Fn::GetAtt:
#       - WindowsInstance
#       - PublicDnsName
#     Condition: CreateWindows
#     Description: Web URL for Streaming Server, using DNS Name of the newly created
#       EC2 instance
#   WindowsPublicIp:
#     Value:
#       Fn::GetAtt:
#       - WindowsInstance
#       - PublicIp
#     Condition: CreateWindows
#     Description: Public IP address of the newly created EC2 instance
#   WindowsDcvURL:
#     Value:
#       Fn::Join:
#       - ''
#       - - https://
#         - Fn::GetAtt:
#           - WindowsInstance
#           - PublicIp
#         - ":8443"
#     Condition: CreateWindows
#     Description: Connection URL for web access to the newly created EC2 instance via
#       NICE DCV
